const PRODUCTS=[
{id:1,name:'Assinatura Premium',category:'Assinaturas',price:19.90,desc:'Acesso digital conforme a descrição.'},
{id:2,name:'Pack Gamer',category:'Jogos',price:14.90,desc:'Pacote digital para gamers.'},
{id:3,name:'Gift Card',category:'Jogos',price:25,desc:'Código digital entregue após a compra.'},
{id:4,name:'Produto Especial',category:'Assinaturas',price:9.90,desc:'Oferta especial da Koala Store.'}
];
let cart=JSON.parse(localStorage.getItem('koala_cart')||'[]');
const $=s=>document.querySelector(s);const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
function renderProducts(){const q=$('#search').value.trim().toLowerCase();const list=PRODUCTS.filter(p=>(p.name+' '+p.category+' '+p.desc).toLowerCase().includes(q));const box=$('#products');box.innerHTML='';$('#empty').hidden=list.length>0;list.forEach(p=>{const card=document.createElement('article');card.className='product reveal';card.innerHTML=`<div class="product-image drop" data-slot="prod-${p.id}"><div class="drop-content"><div class="upload-icon">＋</div><b>Arraste a imagem do produto aqui</b><span>ou clique para escolher</span></div><img class="slot-image" alt="${p.name}"></div><div class="product-body"><span class="tag">${p.category}</span><h3>${p.name}</h3><div class="desc">${p.desc}</div><div class="price">${money(p.price)}</div><button class="btn primary wide buy" data-id="${p.id}">Comprar</button></div>`;box.appendChild(card);});setupDrops();observeReveal();loadImages()}
function add(id){const p=PRODUCTS.find(x=>x.id==id);const item=cart.find(x=>x.id==id);if(item)item.q++;else cart.push({id:p.id,q:1});saveCart();showToast('Produto adicionado ao carrinho')}
function saveCart(){localStorage.setItem('koala_cart',JSON.stringify(cart));$('#cartQty').textContent=cart.reduce((s,x)=>s+x.q,0)}
function renderCart(){const box=$('#cartItems');box.innerHTML='';if(!cart.length){box.innerHTML='<p style="color:#91a5ba">Seu carrinho está vazio.</p>'}let total=0;cart.forEach(i=>{const p=PRODUCTS.find(x=>x.id===i.id);total+=p.price*i.q;const r=document.createElement('div');r.className='cart-row';r.innerHTML=`<div><b>${p.name}</b><br><small>${money(p.price)} cada</small></div><div class="qty"><button data-minus="${p.id}">−</button><b>${i.q}</b><button data-plus="${p.id}">+</button></div>`;box.appendChild(r)});$('#cartTotal').textContent=money(total)}
function loadImages(){document.querySelectorAll('[data-slot]').forEach(el=>{const data=localStorage.getItem('koala_img_'+el.dataset.slot);if(data){el.classList.add('has-image');el.querySelector('.slot-image').src=data}})}
function compress(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1500,s=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.84))};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
function setupDrops(){document.querySelectorAll('.drop').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound=1;el.addEventListener('click',()=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>input.files[0]&&saveImage(el,input.files[0]);input.click()});['dragenter','dragover'].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();el.classList.add('drag')}));['dragleave','drop'].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();el.classList.remove('drag')});el.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f&&f.type.startsWith('image/'))saveImage(el,f)})})}
async function saveImage(el,file){try{const data=await compress(file);localStorage.setItem('koala_img_'+el.dataset.slot,data);el.classList.add('has-image');el.querySelector('.slot-image').src=data;showToast('Imagem colocada com sucesso')}catch{showToast('Não foi possível carregar a imagem')}}
function observeReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal:not(.visible)').forEach(e=>io.observe(e))}
$('#loginBtn').onclick=()=>openModal('loginModal');$('#cartBtn').onclick=()=>{renderCart();openModal('cartModal')};document.addEventListener('click',e=>{const b=e.target.closest('.buy');if(b)add(+b.dataset.id);const c=e.target.closest('[data-close]');if(c)closeModal(c.dataset.close);const plus=e.target.closest('[data-plus]');if(plus){const i=cart.find(x=>x.id==plus.dataset.plus);i.q++;saveCart();renderCart()}const minus=e.target.closest('[data-minus]');if(minus){const i=cart.find(x=>x.id==minus.dataset.minus);i.q--;if(i.q<=0)cart=cart.filter(x=>x.id!==i.id);saveCart();renderCart()}});$('#checkout').onclick=()=>showToast('Checkout pronto para conectar ao seu pagamento.');
function snow(){for(let i=0;i<45;i++){const f=document.createElement('i');f.className='flake';const s=2+Math.random()*4;f.style.width=f.style.height=s+'px';f.style.left=Math.random()*100+'%';f.style.animationDuration=7+Math.random()*9+'s';f.style.animationDelay=-Math.random()*12+'s';$('#snow').appendChild(f)}}
snow();saveCart();renderProducts();setupDrops();observeReveal();loadImages();
