const products=[
{id:'assinaturas',name:'Assinaturas',category:'Assinaturas',price:0,desc:'Essa função será adicionada em breve.',soon:true,image:PRODUCT_IMAGES.assinaturas},
{id:'nitro',name:'Nitro Discord',category:'Discord',price:6.99,desc:'Produto digital Discord.',image:PRODUCT_IMAGES.nitro},
{id:'texturas',name:'Texturas de Minecraft',category:'Jogos',price:2.00,desc:'Texturas digitais para Minecraft.',image:PRODUCT_IMAGES.texturas}];
let cart=JSON.parse(localStorage.getItem('koalaCart')||'[]');let logged=localStorage.getItem('koalaLogged')==='1';let checkoutFromCart=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function bindEmbeddedImages(){ $$('[data-embedded-image]').forEach(img=>{ const key=img.dataset.embeddedImage; if(PRODUCT_IMAGES[key]) img.src=PRODUCT_IMAGES[key]; }); }
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2200)}
function save(){localStorage.setItem('koalaCart',JSON.stringify(cart));renderCart();}
function requireLogin(action){if(logged){action();return}window.pendingAction=action;$('#loginModal').classList.add('open')}
function login(method){logged=true;localStorage.setItem('koalaLogged','1');$('#loginModal').classList.remove('open');toast('Login '+method+' realizado.');if(window.pendingAction){const a=window.pendingAction;window.pendingAction=null;setTimeout(a,150)}renderHeader()}
function renderHeader(){$('#loginBtn').textContent=logged?'Conta':'Entrar'}
function productCard(p,context='home'){
 const q=Number(sessionStorage.getItem('qty_'+p.id)||1);
 return `<article class="product-card"><div class="product-image ${p.id==='assinaturas'?'subscription-image':''}"><img class="product-icon" src="${p.image}" alt="${p.name}" loading="lazy" decoding="async"></div><div class="product-body"><h3>${p.name}</h3><p>${p.desc}</p>${p.soon?`<div class="soon">Em breve</div><div class="price">R$ 0,00</div><button class="btn full" data-soon>Essa função será adicionada em breve</button>`:`<div class="qty-line"><div class="qty"><button data-minus="${p.id}">−</button><span id="q-${context}-${p.id}">${q}</span><button data-plus="${p.id}">+</button></div><img class="pix-mini" src="${PRODUCT_IMAGES.pix}" alt="Pix"></div><div class="price" id="price-${context}-${p.id}">${money(p.price*q)}</div><button class="btn primary full" data-buy="${p.id}" data-context="${context}">Adicionar ao carrinho</button>`}</div></article>`}
function renderHome(){const q=($('#search')?.value||'').toLowerCase();$('#products').innerHTML=products.filter(p=>(p.name+p.category+p.desc).toLowerCase().includes(q)).map(p=>productCard(p)).join('');bindProductButtons()}
function bindProductButtons(){$$('[data-buy]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.buy);const q=Number(sessionStorage.getItem('qty_'+p.id)||1);requireLogin(()=>addToCart(p,q))});$$('[data-plus]').forEach(b=>b.onclick=()=>changeProductQty(b.dataset.plus,1));$$('[data-minus]').forEach(b=>b.onclick=()=>changeProductQty(b.dataset.minus,-1));$$('[data-soon]').forEach(b=>b.onclick=()=>toast('Essa função será adicionada em breve'))}
function changeProductQty(id,d){const p=products.find(x=>x.id===id);if(!p||p.soon)return;let q=Math.max(1,Math.min(1000,Number(sessionStorage.getItem('qty_'+id)||1)+d));sessionStorage.setItem('qty_'+id,q);const ctx=document.querySelector(`[data-plus="${id}"]`)?.closest('.product-card');if(ctx){const s=ctx.querySelector('[id^="q-"]'),pr=ctx.querySelector('[id^="price-"]');if(s)s.textContent=q;if(pr)pr.textContent=money(p.price*q)}}
function addToCart(p,q){const old=cart.find(x=>x.id===p.id);if(old)old.qty=Math.min(1000,old.qty+q);else cart.push({id:p.id,name:p.name,price:p.price,qty:q,image:p.image});save();toast('Produto adicionado ao carrinho.');}
function renderCategoryCards(){
  const box=$('#categoryGrid');
  if(!box)return;
  const categories=[
    ['Assinaturas',PRODUCT_IMAGES.assinaturas],
    ['Discord',PRODUCT_IMAGES.discordCategory],
    ['Jogos',PRODUCT_IMAGES.texturas]
  ];
  box.innerHTML=categories.map(([name,image])=>`<button class="category-card" data-category="${name}"><span class="cat-art"><img src="${image}" alt="${name}" loading="lazy" decoding="async"></span><b>${name}</b></button>`).join('');
  $$('.category-card').forEach(c=>c.onclick=()=>openCategory(c.dataset.category));
}
function openCategory(cat){$('#homePage').hidden=true;$('#siteFooter').style.display='none';$('#categoryPage').hidden=false;$('#categoryTitle').textContent=cat;$('#categorySubtitle').textContent=cat==='Assinaturas'?'Essa função será adicionada em breve.':'Produtos disponíveis em '+cat+'.';$('#categoryProducts').innerHTML=products.filter(p=>p.category===cat).map(p=>productCard(p,'cat')).join('');bindProductButtons();history.pushState({page:'category',cat},'',`#categoria-${cat.toLowerCase()}`);window.scrollTo(0,0)}
function home(push=true){$('#homePage').hidden=false;$('#categoryPage').hidden=true;$('#checkoutPage').hidden=true;$('#siteFooter').style.display='block';if(push)history.pushState({page:'home'},'', '#inicio');window.scrollTo(0,0);renderHome()}
renderCategoryCards();$$('[data-home]').forEach(e=>e.onclick=()=>home());
function openDrawer(){renderCart();$('#cartDrawer').classList.add('open');$('#drawerOverlay').classList.add('open')}function closeDrawer(){$('#cartDrawer').classList.remove('open');$('#drawerOverlay').classList.remove('open')}
function renderCart(){const box=$('#cartItems');$('#cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);if(!cart.length){box.innerHTML='<div class="cart-empty">Seu carrinho está vazio.</div>';$('#cartTotal').textContent='R$ 0,00';return}box.innerHTML=cart.map(x=>`<div class="cart-row"><img src="${x.image||PRODUCT_IMAGES.logo}" alt="${x.name}"><div><h4>${x.name}</h4><small>${money(x.price)} cada</small><div class="cart-actions"><button data-cart-minus="${x.id}">−</button><b>${x.qty}</b><button data-cart-plus="${x.id}">+</button></div></div><button class="cart-remove" data-cart-remove="${x.id}">×</button></div>`).join('');const total=cart.reduce((a,b)=>a+b.price*b.qty,0);$('#cartTotal').textContent=money(total);$$('[data-cart-plus]').forEach(b=>b.onclick=()=>cartQty(b.dataset.cartPlus,1));$$('[data-cart-minus]').forEach(b=>b.onclick=()=>cartQty(b.dataset.cartMinus,-1));$$('[data-cart-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.cartRemove);save()})}
function cartQty(id,d){const x=cart.find(a=>a.id===id);if(!x)return;x.qty=Math.max(1,Math.min(1000,x.qty+d));save()}
function openCheckout(){if(!cart.length)return toast('Seu carrinho está vazio.');requireLogin(()=>{closeDrawer();$('#homePage').hidden=true;$('#categoryPage').hidden=true;$('#checkoutPage').hidden=false;$('#siteFooter').style.display='none';history.pushState({page:'checkout'},'', '#checkout');renderCheckout();window.scrollTo(0,0)})}
function renderCheckout(){const total=cart.reduce((a,b)=>a+b.price*b.qty,0);$('#payAmount').textContent=money(total);$('#checkoutSubtotal').textContent=money(total);$('#checkoutTotal').textContent=money(total);$('#checkoutItems').innerHTML=cart.map(x=>`<div class="checkout-item"><img src="${x.image||PRODUCT_IMAGES.logo}" alt="${x.name}"><div><h4>${x.name}</h4><small>${money(x.price)} × ${x.qty}</small><div class="cart-actions"><button data-check-minus="${x.id}">−</button><b>${x.qty}</b><button data-check-plus="${x.id}">+</button></div></div><button class="remove" data-check-remove="${x.id}">×</button></div>`).join('');$$('[data-check-plus]').forEach(b=>b.onclick=()=>checkoutQty(b.dataset.checkPlus,1));$$('[data-check-minus]').forEach(b=>b.onclick=()=>checkoutQty(b.dataset.checkMinus,-1));$$('[data-check-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.checkRemove);save();if(!cart.length)home();else renderCheckout()})}
function checkoutQty(id,d){cartQty(id,d);if(cart.length)renderCheckout();else home()}
function buildCountries(){const c=[['🇧🇷','Brasil','+55'],['🇺🇸','Estados Unidos','+1'],['🇨🇦','Canadá','+1'],['🇲🇽','México','+52'],['🇦🇷','Argentina','+54'],['🇨🇱','Chile','+56'],['🇨🇴','Colômbia','+57'],['🇵🇪','Peru','+51'],['🇺🇾','Uruguai','+598'],['🇵🇾','Paraguai','+595'],['🇧🇴','Bolívia','+591'],['🇵🇹','Portugal','+351'],['🇪🇸','Espanha','+34'],['🇫🇷','França','+33'],['🇩🇪','Alemanha','+49'],['🇮🇹','Itália','+39'],['🇬🇧','Reino Unido','+44'],['🇮🇪','Irlanda','+353'],['🇳🇱','Países Baixos','+31'],['🇧🇪','Bélgica','+32'],['🇨🇭','Suíça','+41'],['🇦🇹','Áustria','+43'],['🇸🇪','Suécia','+46'],['🇳🇴','Noruega','+47'],['🇩🇰','Dinamarca','+45'],['🇫🇮','Finlândia','+358'],['🇵🇱','Polônia','+48'],['🇨🇿','Tchéquia','+420'],['🇬🇷','Grécia','+30'],['🇹🇷','Turquia','+90'],['🇮🇱','Israel','+972'],['🇦🇪','Emirados Árabes Unidos','+971'],['🇿🇦','África do Sul','+27'],['🇪🇬','Egito','+20'],['🇳🇬','Nigéria','+234'],['🇮🇳','Índia','+91'],['🇨🇳','China','+86'],['🇯🇵','Japão','+81'],['🇰🇷','Coreia do Sul','+82'],['🇦🇺','Austrália','+61'],['🇳🇿','Nova Zelândia','+64'],['🇸🇬','Singapura','+65'],['🇮🇩','Indonésia','+62'],['🇵🇭','Filipinas','+63'],['🇹🇭','Tailândia','+66'],['🇻🇳','Vietnã','+84'],['🇲🇾','Malásia','+60'],['🇷🇺','Rússia','+7'],['🇺🇦','Ucrânia','+380']];$('#countrySelect').innerHTML=c.map(x=>`<option value="${x[2]}">${x[0]} ${x[2]} — ${x[1]}</option>`).join('')}
$('#cartBtn').onclick=openDrawer;$('#closeCart').onclick=closeDrawer;$('#drawerOverlay').onclick=closeDrawer;$('#checkoutBtn').onclick=openCheckout;$('#checkoutBack').onclick=()=>{home();openDrawer()};$('#supportBtn').onclick=()=>$('#supportModal').classList.add('open');$$('[data-unavailable]').forEach(b=>b.onclick=()=>toast(b.dataset.unavailable));$('#loginBtn').onclick=()=>$('#loginModal').classList.add('open');$('#discordLogin').onclick=()=>login('Discord');$('#googleLogin').onclick=()=>login('Google');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));
$('#payBtn').onclick=()=>{if(!$('#buyerName').value.trim()||!$('#buyerEmail').value.trim()||!$('#buyerPhone').value.trim())return toast('Preencha seus dados de contato.');if(!$('#terms').checked)return toast('Aceite os termos e condições para continuar.');toast('Checkout pronto para integração com Pix.')};$('#search').addEventListener('input',renderHome);
window.onpopstate=()=>{const h=location.hash;if(h==='#checkout'){openCheckout()}else if(h.startsWith('#categoria-')){const cat=h.split('-')[1];openCategory(cat.charAt(0).toUpperCase()+cat.slice(1))}else home(false)};
function snow(){const count=matchMedia('(max-width:560px)').matches?12:28,frag=document.createDocumentFragment();for(let i=0;i<count;i++){const f=document.createElement('i');f.className='flake';const s=2+Math.random()*3;f.style.width=f.style.height=s+'px';f.style.left=Math.random()*100+'%';f.style.animationDuration=(18+Math.random()*16)+'s';f.style.animationDelay=(-Math.random()*30)+'s';frag.appendChild(f)}$('#snow').appendChild(frag)}
bindEmbeddedImages();buildCountries();renderHome();renderCart();renderHeader();snow();
