const products=[
{name:'Assinaturas',category:'Assinaturas',price:0,desc:'Essa função será adicionada em breve.',key:'assinaturas'},
{name:'Nitro Discord',category:'Discord',price:6.99,desc:'Produto digital para Discord.',key:'nitro'},
{name:'Texturas de Minecraft',category:'Jogos',price:2.00,desc:'Texturas digitais para Minecraft.',key:'texturas'}
];
let cart=JSON.parse(localStorage.getItem('koala-cart')||'[]');
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function imageZone(key,label,cls='product-img'){const saved=localStorage.getItem('koala-img-'+key);return `<div class="drop-zone ${cls} ${saved?'has-image':''}" data-key="${key}" data-label="${esc(label)}">${saved?`<img src="${saved}" alt="">`:'<span>ARRASTE O ARQUIVO</span>'}</div>`}
function card(p){const i=products.indexOf(p);return `<article class="product"><div>${imageZone('product-'+p.key,'Imagem do produto '+p.name)}</div><div class="product-body"><span class="badge">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p>${p.price===0?`<div class="soon-label">Em breve</div><div class="price">R$ 0,00</div><button class="btn full" onclick="soon()">Disponível em breve</button>`:`<div class="qty-control"><button onclick="changeQty(${i},-1)">−</button><span id="qty-${i}">1</span><button onclick="changeQty(${i},1)">+</button></div><div class="price" id="price-${i}">${money(p.price)}</div><button class="btn primary full" onclick="addCart(${i})">Adicionar ao carrinho</button>`}</div></article>`}
function render(list=products,target='products'){document.getElementById(target).innerHTML=list.map(card).join('');bindDropZones()}
function filterCategory(cat){document.getElementById('categoriaArea').classList.remove('hidden');document.getElementById('categorias').classList.add('hidden-section');document.getElementById('produtos').classList.add('hidden-section');document.getElementById('avaliacoes').classList.add('hidden-section');document.getElementById('categoryTitle').textContent=cat;document.getElementById('categoryText').textContent=`Produtos da categoria ${cat}.`;render(products.filter(p=>p.category===cat),'categoryProducts');window.scrollTo({top:0,behavior:'smooth'})}
function closeCategory(){document.getElementById('categoriaArea').classList.add('hidden');document.getElementById('categorias').classList.remove('hidden-section');document.getElementById('produtos').classList.remove('hidden-section');document.getElementById('avaliacoes').classList.remove('hidden-section');window.scrollTo({top:0,behavior:'smooth'})}
function renderSearch(){const q=document.getElementById('search').value.toLowerCase().trim();render(products.filter(p=>(p.name+' '+p.category+' '+p.desc).toLowerCase().includes(q)),'products')}
function addCart(i){const p=products[i];if(!p.price)return soon();const qty=Math.max(1,Math.min(1000,Number(document.getElementById('qty-'+i)?.textContent||1)));const old=cart.find(x=>x.key===p.key);if(old)old.qty=Math.min(1000,old.qty+qty);else cart.push({key:p.key,name:p.name,price:p.price,qty});saveCart();toast('Produto adicionado ao carrinho.')}
function changeQty(i,d){const e=document.getElementById('qty-'+i);if(!e)return;const q=Math.max(1,Math.min(1000,Number(e.textContent)+d));e.textContent=q;document.getElementById('price-'+i).textContent=money(products[i].price*q)}
function saveCart(){localStorage.setItem('koala-cart',JSON.stringify(cart));updateCart()}
function updateCart(){document.getElementById('cartQty').textContent=cart.reduce((a,p)=>a+p.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><div><b>${esc(p.name)}</b><small>${money(p.price)} × ${p.qty}</small></div><b>${money(p.price*p.qty)}</b></div>`).join(''):'<div class="cart-empty">Seu carrinho está vazio.</div>';document.getElementById('cartTotal').textContent=money(cart.reduce((a,p)=>a+p.price*p.qty,0))}
function modal(id,open=true){document.getElementById(id).classList.toggle('open',open)}
function soon(){toast('Essa função será adicionada em breve')}
function toast(t){const e=document.getElementById('toast')||(()=>{const x=document.createElement('div');x.id='toast';x.className='toast';document.body.appendChild(x);return x})();e.textContent=t;e.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>e.classList.remove('show'),2200)}
function bindDropZones(){document.querySelectorAll('.drop-zone').forEach(z=>{if(z.dataset.bound)return;z.dataset.bound='1';if(z.classList.contains('has-image'))return;z.addEventListener('click',()=>pick(z));z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('dragover')});z.addEventListener('dragleave',()=>z.classList.remove('dragover'));z.addEventListener('drop',e=>{e.preventDefault();z.classList.remove('dragover');const f=e.dataTransfer.files[0];if(f)saveImage(z,f)})})}
function pick(z){if(z.classList.contains('has-image'))return;const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>input.files[0]&&saveImage(z,input.files[0]);input.click()}
function saveImage(z,file){if(z.classList.contains('has-image'))return;if(!file.type.startsWith('image/'))return toast('Escolha uma imagem.');const r=new FileReader();r.onload=()=>{try{localStorage.setItem('koala-img-'+z.dataset.key,r.result);z.classList.add('has-image');z.innerHTML=`<img src="${r.result}" alt="">`;toast('Imagem adicionada. Ela não pode ser removida pela página.')}catch(e){toast('A imagem é grande demais. Use uma menor.')}};r.readAsDataURL(file)}
document.querySelectorAll('.category-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('.drop-zone'))return;filterCategory(c.dataset.category)}));document.getElementById('showAll').onclick=closeCategory;document.getElementById('search').addEventListener('input',renderSearch);document.getElementById('loginBtn').onclick=()=>modal('loginModal');document.getElementById('cartBtn').onclick=()=>modal('cartModal');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));document.getElementById('discordLogin').onclick=()=>toast('Login Discord será conectado ao seu Supabase.');document.getElementById('googleLogin').onclick=()=>toast('Login Google será conectado ao seu Supabase.');document.getElementById('checkout').onclick=()=>toast('Checkout será conectado na próxima etapa.');
document.getElementById('reviewForm').addEventListener('submit',e=>{e.preventDefault();const a=JSON.parse(localStorage.getItem('koala-reviews')||'[]');a.unshift({name:document.getElementById('reviewName').value.trim(),text:document.getElementById('reviewText').value.trim(),stars:+document.getElementById('reviewStars').value});localStorage.setItem('koala-reviews',JSON.stringify(a.slice(0,30)));e.target.reset();renderReviews();toast('Avaliação publicada.')});
function renderReviews(){const a=JSON.parse(localStorage.getItem('koala-reviews')||'[]');document.getElementById('reviews').innerHTML=a.map(r=>`<article class="review"><div class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</div><b>${esc(r.name)}</b><p>${esc(r.text)}</p></article>`).join('')||'<article class="review"><div class="stars">★★★★★</div><b>Seja o primeiro</b><p>Conte como foi sua experiência.</p></article>'}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
function snow(){const s=document.getElementById('snow');for(let i=0;i<34;i++){const f=document.createElement('i');f.className='flake';f.style.left=Math.random()*100+'%';f.style.width=f.style.height=(2+Math.random()*3)+'px';f.style.opacity=.22+Math.random()*.38;f.style.animationDuration=(18+Math.random()*16)+'s';f.style.animationDelay=(-Math.random()*30)+'s';s.appendChild(f)}}
snow();render();renderReviews();updateCart();bindDropZones();
