const products=[
{id:1,name:'Assinaturas de Streaming',cat:'assinaturas',price:0,soon:true,icon:'▶'},
{id:2,name:'Discord Nitro',cat:'discord',price:6,soon:false,icon:'◉'},
{id:3,name:'Texturas de Minecraft',cat:'jogos',price:2,soon:false,icon:'◆'}
];
const reviews=[['Pedro Vitor Marques Rodrigues','Voltarei a comprar.'],['Milena De Sousa Araujo','Muito bom.'],['Lucca Galante','Entrega rápida. Confiável. Ótimo suporte.'],['Leonardo Filipe Melo','Ótimo produto.'],['Willian Jesus','Entrega rápida. Confiável.'],['Breno','Muito bom haha.']];
const cats={assinaturas:'Assinaturas',discord:'Discord',jogos:'Jogos'};
let cart=JSON.parse(localStorage.getItem('koala_cart')||'[]');
const $=s=>document.querySelector(s);
function money(n){return n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function save(){localStorage.setItem('koala_cart',JSON.stringify(cart));renderCart();}
function add(id){const p=products.find(x=>x.id===id);if(!p||p.soon){toast('Este produto está em breve.');return}const q=Math.max(1,Math.min(1000,Number($('#q-'+id)?.value||1)));let item=cart.find(x=>x.id===id);if(item)item.qty=Math.min(1000,item.qty+q);else cart.push({id,qty:q});save();toast('Produto adicionado ao carrinho.');}
function setQty(id,delta){let item=cart.find(x=>x.id===id);if(!item)return;item.qty=Math.max(1,Math.min(1000,item.qty+delta));save()}
function remove(id){cart=cart.filter(x=>x.id!==id);save()}
function renderCart(){const el=$('#cartItems');if(!el)return;$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);if(!cart.length){el.innerHTML='<div class="empty">Seu carrinho está vazio.<br>Escolha um produto para começar.</div>';$('#cartTotal').textContent=money(0);return}let total=0;el.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);const sub=p.price*x.qty;total+=sub;return `<div class="cart-row"><div class="cart-thumb">${p.icon}</div><div><div class="cart-name">${p.name}</div><div class="cart-price">${money(p.price)} cada</div><div class="qty"><button onclick="setQty(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="setQty(${p.id},1)">+</button></div><button class="remove" onclick="remove(${p.id})">Remover</button></div><div class="row-total">${money(sub)}</div></div>`}).join('');$('#cartTotal').textContent=money(total)}
function productCard(p){return `<article class="product-card reveal"><span class="badge">${p.soon?'EM BREVE':'DISPONÍVEL'}</span><div class="product-art">${p.id===1?'<div class="big-icon">▶</div>':p.id===2?'<div class="discord-mark">◉</div>':'<div class="big-icon">◆</div>'}</div><div class="product-info"><h3>${p.name}</h3>${p.soon?'<div class="soon">Em breve</div>':`<div class="price">${money(p.price)}</div><div class="pixline"><span class="pixlogo">◆</span> à vista no Pix</div>`}<div class="product-actions">${p.soon?'<button class="mini" onclick="toast(\'Produto em breve.\')">Ver detalhes</button>':`<button class="mini" onclick="openProduct(${p.id})">Detalhes</button><button class="buy" onclick="add(${p.id})">Adicionar</button>`}</div></div></article>`}
function catCard(key,label){const art=key==='assinaturas'?'<div class="cat-icon">▶</div>':key==='discord'?'<div class="cat-icon">◉</div>':'<div class="cat-icon">◆</div>';return `<a class="cat-card reveal" href="#categoria/${key}"><div class="cat-art ${key}-art">${art}</div><h3>${label}</h3><p>${products.filter(p=>p.cat===key).length} produto${products.filter(p=>p.cat===key).length>1?'s':''}</p></a>`}
function home(){return `<section class="hero"><div class="hero-inner"><div class="reveal"><span class="eyebrow"><i></i> Loja digital • entrega rápida</span><h1>Temos tudo que você <span>quer.</span></h1><p>Produtos digitais, Discord e jogos em um só lugar. Navegue pelas categorias, escolha sua quantidade e monte seu pedido.</p><div class="hero-buttons"><a class="primary" href="#destaques">Ver produtos →</a><a class="secondary" href="#categorias">Explorar categorias</a></div></div><div class="hero-card reveal"><span class="floating one">⚡ entrega imediata</span><img class="hero-logo" src="assets/koala-logo.jpg" alt="Logo Koala Store"><span class="floating two">🔒 compra segura</span></div></div></section>
<section class="section" id="categorias"><div class="section-head"><div><small>CATEGORIAS</small><h2>Categorias populares</h2><p>Encontre o que você procura rapidamente.</p></div><a class="text-link" href="#categorias">Ver todas →</a></div><div class="cat-grid stagger">${Object.entries(cats).map(([k,v])=>catCard(k,v)).join('')}</div></section>
<section class="featured" id="destaques"><div class="section"><div class="section-head"><div><small>DESTAQUE</small><h2>Produtos em destaque</h2><p>Os produtos disponíveis na Koala Store.</p></div></div><div class="product-grid stagger">${products.map(productCard).join('')}</div></div></section>
<section class="trust"><div class="trust-grid stagger"><div class="trust-item"><b>⚡ Entrega rápida</b><span>Processo pensado para produtos digitais.</span></div><div class="trust-item"><b>🔒 Compra segura</b><span>Seus dados devem ser tratados com cuidado.</span></div><div class="trust-item"><b>💬 Suporte</b><span>Canais de atendimento sempre à disposição.</span></div><div class="trust-item"><b>◆ Pix</b><span>Pagamento rápido e simples.</span></div></div></section>
<section class="section"><div class="section-head"><div><small>DEPOIMENTOS DE CLIENTES</small><h2>Experiências de quem compra</h2><p>Avaliações demonstrativas para a loja.</p></div></div><div class="testimonials stagger">${reviews.map((r,i)=>`<article class="review"><div class="review-top"><div class="avatar">${r[0].split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h4>${r[0]}</h4><small>Cliente Koala Store</small></div></div><div class="stars">★★★★★</div><p>${r[1]}</p><a href="#destaques">Ver produtos →</a></article>`).join('')}</div></section>
<section class="section"><div class="blog-box"><div><h2>Conteúdo e novidades</h2><p>Área preparada para blog, novidades e guias da Koala Store.</p></div><button class="secondary" onclick="toast('Blog em construção.')">Acessar blog →</button></div></section>`}
function categoryPage(key){const label=cats[key];const list=products.filter(p=>p.cat===key);return `<div class="page"><div class="section-head"><div><small>CATEGORIA</small><h2>${label}</h2><p>Produtos da categoria ${label.toLowerCase()}.</p></div><a class="text-link" href="#inicio">← Voltar</a></div><div class="product-grid stagger">${list.map(productCard).join('')}</div></div>`}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('#searchModal').classList.add('show');$('#searchInput').value=p.name;showSearch(p.name)}
function login(){return `<div class="page"><div class="login-wrap"><section class="login-info reveal"><img src="assets/koala-logo.jpg" alt="Koala Store"><h1>Fazer login</h1><p>Entre com sua conta para continuar. Nesta versão, os botões de provedor são demonstrativos e não fazem OAuth real sem credenciais/configuração.</p></section><section class="login-card reveal"><h2>Fazer login</h2><p>Entre com sua conta para continuar.</p><button class="provider" onclick="toast('OAuth do Google precisa ser configurado no projeto.')"><span class="google-mark">G</span> Entrar com Google</button><div class="or">ou</div><button class="provider" onclick="toast('OAuth do Discord precisa ser configurado no projeto.')"><span class="discord-mark2">◉</span> Entrar com Discord</button><div style="margin-top:22px"><a class="secondary" href="#inicio" style="display:block;text-align:center">Voltar para a loja</a></div></section></div></div>`}
function checkout(){if(!cart.length){toast('Seu carrinho está vazio.');location.hash='#destaques';return}let total=cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);return `<div class="page"><div class="section-head"><div><small>FINALIZAÇÃO</small><h2>Pagamento</h2><p>Confira seu pedido antes de continuar.</p></div><a class="text-link" href="#inicio">← Voltar</a></div><div class="checkout-grid"><section class="panel reveal"><h2>Forma de pagamento</h2><div class="method"><div class="method-icon">◆</div><div><strong>Pix</strong><small>Mais rápido • pagamento instantâneo</small></div></div><div style="margin-top:22px"><button class="primary" style="width:100%" onclick="toast('Checkout demonstrativo: conecte seu gateway Pix para cobrar de verdade.')">Gerar pagamento Pix</button></div></section><section class="panel reveal"><h2>Resumo</h2>${cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="order-line"><span>${p.name} × ${x.qty}</span><strong>${money(p.price*x.qty)}</strong></div>`}).join('')}<div class="sum" style="margin-top:16px"><span>Total</span><strong>${money(total)}</strong></div></section></div></div>`}
function notFound(){return `<div class="not-found"><h1>404</h1><p>Página não encontrada.</p><a class="primary" href="#inicio">Voltar ao início</a></div>`}
function route(){let hash=location.hash.replace('#','')||'inicio';let content;if(hash==='inicio')content=home();else if(hash==='categorias')content=home();else if(hash==='destaques')content=home();else if(hash==='login')content=login();else if(hash==='checkout')content=checkout();else if(hash==='termos'){content=home();setTimeout(()=>$('#termsModal').classList.add('show'),20)}else if(hash.startsWith('categoria/')){const k=hash.split('/')[1];content=cats[k]?categoryPage(k):notFound()}else content=notFound();$('#main').innerHTML=content;window.scrollTo({top:0,behavior:'instant'});initReveal();if(hash==='checkout')renderCart()}
function initReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal,.stagger').forEach(x=>io.observe(x))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2300)}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');$('#backdrop').classList.add('show')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#backdrop').classList.remove('show')}
function showSearch(q){const list=products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));$('#searchResults').innerHTML=list.length?list.map(p=>`<div class="search-result"><div><b>${p.name}</b><span>${p.soon?'Em breve':money(p.price)}</span></div><button class="buy" onclick="${p.soon?`toast('Produto em breve.')`:`add(${p.id})`}">${p.soon?'Em breve':'Adicionar'}</button></div>`).join(''):'<div class="empty">Nenhum produto encontrado.</div>'}
$('#supportBtn').addEventListener('click',e=>{e.stopPropagation();$('#supportPop').classList.toggle('show')});document.addEventListener('click',e=>{if(!e.target.closest('.support-pop')&&!e.target.closest('#supportBtn'))$('#supportPop').classList.remove('show')});$('#cartBtn').addEventListener('click',openCart);$('#backdrop').addEventListener('click',closeCart);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.close;$('#'+id).classList.remove('show')}));$('#searchBtn').addEventListener('click',()=>{$('#searchModal').classList.add('show');setTimeout(()=>$('#searchInput').focus(),50)});$('#searchInput').addEventListener('input',e=>showSearch(e.target.value));$('#checkoutBtn').addEventListener('click',()=>{closeCart();location.hash='#checkout'});window.addEventListener('hashchange',route);window.addEventListener('load',()=>{route();renderCart()});
